[package]
name = "cotli-helper"
version = "0.1.0"
authors = ["Sean Griffin <sean@seantheprogrammer.com>"]

[dependencies]
bitflags = "0.8.2"
itertools = "0.6.0"
ordermap = "0.2.10"
rand = "0.3.15"
clap = "2.24.2"

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true
